# Generated by Django 6.0 on 2025-12-12 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Destination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_slots', models.PositiveIntegerField(default=0, verbose_name='Total Capacity')),
                ('available_slots', models.PositiveIntegerField(default=0, verbose_name='Available Slots')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='Destination.destination', verbose_name='Related Destination')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'unique_together': {('destination',)},
            },
        ),
    ]
